version: '3'

services:
  besu:
    image: hyperledger/besu:20.10
    container_name: besu
    ports:
      - "30303/tcp"
      - "30303/udp"
      - "8545:8545"
      - "8546:8546"
    environment:
      BESU_GENESIS_FILE: /etc/besu/genesis.json
      BESU_MINER_ENABLED: 'true'
      BESU_MINER_COINBASE: fe3b557e8fb62b89f4916b721be55ceb828dbd73
      BESU_RPC_HTTP_ENABLED: 'true'
      BESU_HOST_WHITELIST: 'all'
      BESU_RPC_HTTP_API: 'ADMIN,ETH,MINER,NET,WEB3'
      BESU_RPC_HTTP_CORS_ORIGINS: "*"
      BESU_RPC_HTTP_ENABLED: 'true'
      BESU_RPC_HTTP_HOST: '0.0.0.0'
      BESU_PRUNING_ENABLED: 'true'
    volumes:
      - ./config/besu/:/etc/besu

  teku:
#    image: teku:local
    image: pegasyseng/teku:0.12.7
    container_name: teku
    entrypoint: '/opt/teku/entrypoint.sh'
    environment:
      EP_ETH1_ENDPOINT: 'http://besu:8545'
      EP_ETH1_PRIVATE_KEY: '<private key>'
      EP_DEPOSIT_CONTRACT_ADDRESS: '0xdddddddddddddddddddddddddddddddddddddddd'
      EP_KEYSTORE_VALIDATOR_PASSWORD: 'password'
      EP_KEYSTORE_WITHDRAW_PASSWORD: 'password'
    volumes:
      - ./bin/teku/entrypoint.sh:/opt/teku/entrypoint.sh
      - ./config/teku/teku.yml:/tmp/teku.yml
